import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>jiangwenyang</title>
        <meta name="description" content="Generated by jiangwenyang" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="text-red-200 text-4xl">test</div>
      </main>
    </>
  );
}
